name: CI/CD for Go API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Etapa de Build e Teste
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Check out o código do repositório
      - name: Check out code
        uses: actions/checkout@v4

      # Configuração do Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      # Instala dependências e faz build
      - name: Install dependencies and build
        run: |
          go mod tidy
          go build -v ./...

      # Executa os testes
      - name: Run tests
        run: |
          go test -v ./...

  # Etapa de Build e Push para Docker Hub
  docker:
    runs-on: ubuntu-latest
    needs: build_and_test  # Depende do sucesso do build e teste

    steps:
      # Check out o código do repositório
      - name: Check out code
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Configurar no GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Configurar no GitHub Secrets

      # Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-agendamento:latest .

      # Push da imagem para o Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api-agendamento:latest
