name: CI for Go API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Etapa de Build e Teste
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Check out o código do repositório
      - name: Check out code
        uses: actions/checkout@v4

      # Configuração do Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      # Instala dependências e faz build
      - name: Install dependencies and build
        run: |
          go mod tidy
          go build -v ./...

      # Executa os testes
      - name: Run tests
        run: |
          go test -v ./...
